### ISSUE TITLE
Computing homographies

### ISSUE THREAD

**Issue by AlexSS1001** [erikalu/omnimatte#14]
Hello,

I am having trouble with point 6) in the custom video training steps. How do you compute the initial homographies.txt file? In the readme it just says "use OpenCV". Can you please share the script for the initial generation of homographies that you used for the "tennis" dataset?

**Comment by erikalu** [comment]
The stabilization code that was used to compute the homographies is currently internal to Google, so we aren't able to release it.

If the camera motion isn't large and you don't need to preserve it, you could find existing software to produce a stabilized version of your video, run Omnimatte on that video, and just use the identity for the homographies file ```1 0 0 0 1 0 0 0 1```

Otherwise, [this OpenCV code](https://learnopencv.com/feature-based-image-alignment-using-opencv-c-python/) can be helpful for computing the homographies directly.

**Comment by AlexSS1001** [comment]
I have found something similar and it seems to be working ok. Thanks.

**Comment by o98k-ok** [comment]
> I have found something similar and it seems to be working ok. Thanks.

Can you share your script, I really need that. thanks.
